apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-app
  labels:
    app: api-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: api-app
        image: localhost:5000/local/api-app:latest
        command:
        ports:
          - containerPort: 8080
